version: "3"
services:
  drivenOps_db:
    image: postgres
    container_name: drivenOps_db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env

  node_app:
    container_name: node_app
    build: ./back-end/.
    ports:
      - 80:5000
    env_file:
      - ./back-end/.env
    depends_on:
      - drivenOps_db