version: "3"
services:
  drivenOps_db:
    image: postgres
    container_name: drivenOps_db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env
    volumes:
      - pg:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: ./back-end/.
    ports:
      - 80:5000
    env_file:
      - ./back-end/.env
    depends_on:
      - drivenOps_db

  react_app:
    container_name: react_app
    build: ./front-end
    volumes:
      - nginx_react:/var/www/html
  
  nginx_server:
    container_name: nginx_server
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - nginx_react:/var/www/html
    depends_on:
      - drivenOps_db
      - node_app
      - react_app


volumes:
  pg:
  nginx_react: