version: "3"
services:
  drivenOps_db:
    image: postgres
    container_name: drivenOps_db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.test

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - drivenOps_db